### ISSUE TITLE
JWT authentication configuration mismatched

### ISSUE THREAD

**Issue by emanuel-virca** [AzureMediaServicesSamples/Key-delivery-with-AAD-integration#3]
Hello, I am new to azure AD and any kind of authentication so forgive me if I am wrong.

I have tried to run the project and i have managed to authenticate using an account i have created in my AD. The claims has all been set.
Now i have seen you area saving the jwt claim as Configuration.ClaimsSignInJwtToken and running it i can see the RowData is present and gets saved in the claims. However, the way claim value is accessed it's a little bit confusing as in the MediaLibraryController.GetJwtSecurityToken method the claims is trying to be accessed using a property in configuration that is not specified in the appconfig, and wich is KdResourceId.
The other think that I do not understand is why authContext.TokenCache.ReadItems() return only the AD token when I can see in owinContext.Authentication.User.Claims other claims present.

Can you help me on this? Is there a configuration mismatch?

**Comment by bratland** [comment]
I have the same problem! Any chance we might get an update on this?

**Comment by gtrifonov** [comment]
Added missing config section and instruction how to register another application which act as resource for which jwt token should be issued. Token issued for this resource will be used to request content key for decryption. Azure Media Key Delivery  Services validating that claims are matching and serving content key.
